name: Vercel Deployment

on:
  push:
    branches:
      - main  # Change this to your desired branch, e.g., 'master' or 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set the Node.js version you are using

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
      
      - name: Build project
        run: |
          CI=false npm run build  # Ignore warnings during the build

      - name: Deploy to Vercel
        run: |
          curl -fsSL https://vercel.com/download -o vercel-linux.tar.gz
          tar -xzf vercel-linux.tar.gz
          sudo mv vercel /usr/local/bin
          echo "${{ secrets.VERCEL_TOKEN }}" | vercel login --token
          vercel --prod  # Deploy your app to Vercel (use --prod for production deployment)
